// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCe-NKg_RHfTqcxIM52iiKJo5HgI4Yen0',
    appId: '1:948036574790:web:11eeb3a2dc5e51f6e43447',
    messagingSenderId: '948036574790',
    projectId: 'fir-c288e',
    authDomain: 'fir-c288e.firebaseapp.com',
    storageBucket: 'fir-c288e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3QmfKMr8WixYS1ypFbcxc9jmXX20snRM',
    appId: '1:948036574790:android:7104e37d35fb3422e43447',
    messagingSenderId: '948036574790',
    projectId: 'fir-c288e',
    storageBucket: 'fir-c288e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Z8tNfAPpwv0eNiUoRFFQIZ8uCnq0gME',
    appId: '1:948036574790:ios:664f10dc9c64cc17e43447',
    messagingSenderId: '948036574790',
    projectId: 'fir-c288e',
    storageBucket: 'fir-c288e.appspot.com',
    iosBundleId: 'com.example.riderFirebaseOak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Z8tNfAPpwv0eNiUoRFFQIZ8uCnq0gME',
    appId: '1:948036574790:ios:9cc19f20255d5ac4e43447',
    messagingSenderId: '948036574790',
    projectId: 'fir-c288e',
    storageBucket: 'fir-c288e.appspot.com',
    iosBundleId: 'com.example.riderFirebaseOak.RunnerTests',
  );
}
